#### Handling Imbalanced Dataset with Machine Learning

In [ ]:
import pandas as pd
df=pd.read_csv('ais_disabling_events_main_only_imp_col_csv.csv')
df.head()

vessel_class  gap_hours  iuu_caught  spherical_distances  eez_check  \
0        other  13.016667           0           207.942845          0   
1        other  13.850000           0             9.704232          0   
2        other  33.733333           0            10.789069          1   
3        other  30.650000           0            11.695860          1   
4        other  50.283333           0            93.113335          1   

  Ocean List New whose false were in OG  
0                              atlantic  
1                              atlantic  
2                              atlantic  
3                              atlantic  
4                              atlantic

In [ ]:
df.shape

(55368, 6)

In [ ]:
df['iuu_caught'].value_counts()

0    55268
1      100
Name: iuu_caught, dtype: int64

In [ ]:
#### Independent and Dependent Features
X=df.drop("iuu_caught",axis=1)
y=df.iuu_caught

### One Hot Encoding

In [ ]:
print(df['vessel_class'].unique())
print(df['Ocean List New whose false were in OG'].unique())

['other' 'trawlers' 'squid_jigger' 'tuna_purse_seines'
 'drifting_longlines']
['atlantic' 'southern' 'mediterranean' 'arctic' 'pacific' 'Pacific'
 'FALSE' 'indian']


In [ ]:
print(df['vessel_class'].value_counts())
print(df['Ocean List New whose false were in OG'].value_counts())

drifting_longlines    18641
squid_jigger          16021
tuna_purse_seines      8620
trawlers               7913
other                  4173
Name: vessel_class, dtype: int64
pacific          17108
atlantic         16469
Pacific          14762
indian            6176
arctic             499
FALSE              227
southern           116
mediterranean       11
Name: Ocean List New whose false were in OG, dtype: int64


In [ ]:
one_hot_encoded_data = pd.get_dummies(df, columns = ['vessel_class', 'Ocean List New whose false were in OG'])
print(one_hot_encoded_data.head())

   gap_hours  iuu_caught  spherical_distances  eez_check  \
0  13.016667           0           207.942845          0   
1  13.850000           0             9.704232          0   
2  33.733333           0            10.789069          1   
3  30.650000           0            11.695860          1   
4  50.283333           0            93.113335          1   

   vessel_class_drifting_longlines  vessel_class_other  \
0                                0                   1   
1                                0                   1   
2                                0                   1   
3                                0                   1   
4                                0                   1   

   vessel_class_squid_jigger  vessel_class_trawlers  \
0                          0                      0   
1                          0                      0   
2                          0                      0   
3                          0                      0   
4              

In [ ]:
#### Independent and Dependent Features
X=one_hot_encoded_data.drop("iuu_caught",axis=1)
y=one_hot_encoded_data.iuu_caught

#### Cross Validation Like KFOLD and Hyperpaqrameter Tuning

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [ ]:
10.0 **np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [ ]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [ ]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py", line 447, in _check_solver
    raise ValueError(
ValueError: Solver l

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [ ]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16578     0]
 [   33     0]]
0.9980133646378906
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     16578
           1       0.00      0.00      0.00        33

    accuracy                           1.00     16611
   macro avg       0.50      0.50      0.50     16611
weighted avg       1.00      1.00      1.00     16611



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_train.value_counts()

0    38690
1       67
Name: iuu_caught, dtype: int64

In [ ]:
class_weight=dict({0:1,1:100})

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16578     0]
 [   33     0]]
0.9980133646378906
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     16578
           1       0.00      0.00      0.00        33

    accuracy                           1.00     16611
   macro avg       0.50      0.50      0.50     16611
weighted avg       1.00      1.00      1.00     16611



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#### Under Sampling

In [ ]:
from collections import Counter
Counter(y_train)

Counter({0: 199017, 1: 347})

In [ ]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

c:\users\krish naik\anaconda3\envs\myenv1\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


The number of classes before fit Counter({0: 199017, 1: 347})
The number of classes after fit Counter({0: 433, 1: 347})


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[64448 20850]
 [   10   135]]
0.7558606322343551
              precision    recall  f1-score   support

           0       1.00      0.76      0.86     85298
           1       0.01      0.93      0.01       145

    accuracy                           0.76     85443
   macro avg       0.50      0.84      0.44     85443
weighted avg       1.00      0.76      0.86     85443



##### Over Sampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
os=RandomOverSampler(0.75)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

c:\users\krish naik\anaconda3\envs\myenv1\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


The number of classes before fit Counter({0: 199017, 1: 347})
The number of classes after fit Counter({0: 199017, 1: 149262})


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85292     6]
 [   27   118]]
0.9996137776061234
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85298
           1       0.95      0.81      0.88       145

    accuracy                           1.00     85443
   macro avg       0.98      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



#### SMOTETomek

In [ ]:
from imblearn.combine import SMOTETomek

In [ ]:
from collections import Counter

os=SMOTETomek(0.75)

X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

/usr/local/lib/python3.8/dist-packages/imblearn/utils/_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 38690, 1: 67})
The number of classes after fit Counter({0: 38452, 1: 28779})


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16370   208]
 [   27     6]]
0.9858527481789175
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     16578
           1       0.03      0.18      0.05        33

    accuracy                           0.99     16611
   macro avg       0.51      0.58      0.52     16611
weighted avg       1.00      0.99      0.99     16611



# Neural Networks using TF

In [ ]:
import tensorflow as tf
import keras

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 100, input_shape = (16, ), activation = 'relu'),
])

model.compile(optimizer = 'adam', metrics = ['accuracy'], loss = 'mean_absolute_error')

model.summary()

model.fit(X_train_ns, y_train_ns, epochs = 50)

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 100)               1700      
                                                                 
Total params: 1,700
Trainable params: 1,700
Non-trainable params: 0
_________________________________________________________________
Epoch 1/50
2101/2101 [==============================] - 4s 2ms/step - loss: 1.5798 - accuracy: 0.5032
Epoch 2/50
2101/2101 [==============================] - 4s 2ms/step - loss: 0.4281 - accuracy: 0.5718
Epoch 3/50
2101/2101 [==============================] - 4s 2ms/step - loss: 0.4281 - accuracy: 0.5719
Epoch 4/50
2101/2101 [==============================] - 4s 2ms/step - loss: 0.4281 - accuracy: 0.5719
Epoch 5/50
2101/2101 [==============================] - 4s 2ms/step - loss: 0.4281 - accuracy: 0.5719
Epoch 6/50
2101/2101 [==============================] - 4s 2ms/step - 

In [ ]:
X_test.head()

gap_hours  spherical_distances  eez_check  \
54731   19.550000            40.072388          1   
13552   20.066667            30.839979          0   
43354   17.066667            33.442549          0   
11691  344.683333           139.795048          0   
24738   19.183333            11.064140          0   

       vessel_class_drifting_longlines  vessel_class_other  \
54731                                1                   0   
13552                                0                   0   
43354                                1                   0   
11691                                0                   0   
24738                                0                   0   

       vessel_class_squid_jigger  vessel_class_trawlers  \
54731                          0                      0   
13552                          1                      0   
43354                          0                      0   
11691                          0                      1   
24738                          1                      0   

       vessel_class_tuna_purse_seines  \
54731                               0   
13552                               0   
43354                               0   
11691                               0   
24738                               0   

       Ocean List New whose false were in OG_FALSE  \
54731                                            0   
13552                                            0   
43354                                            0   
11691                                            0   
24738                                            0   

       Ocean List New whose false were in OG_Pacific  \
54731                                              0   
13552                                              0   
43354                                              1   
11691                                              0   
24738                                              1   

       Ocean List New whose false were in OG_arctic  \
54731                                             0   
13552                                             0   
43354                                             0   
11691                                             0   
24738                                             0   

       Ocean List New whose false were in OG_atlantic  \
54731                                               0   
13552                                               1   
43354                                               0   
11691                                               1   
24738                                               0   

       Ocean List New whose false were in OG_indian  \
54731                                             1   
13552                                             0   
43354                                             0   
11691                                             0   
24738                                             0   

       Ocean List New whose false were in OG_mediterranean  \
54731                                                  0     
13552                                                  0     
43354                                                  0     
11691                                                  0     
24738                                                  0     

       Ocean List New whose false were in OG_pacific  \
54731                                              0   
13552                                              0   
43354                                              0   
11691                                              0   
24738                                              0   

       Ocean List New whose false were in OG_southern  
54731                                               0  
13552                                               0  
43354                                               0  
11691                                               0  
24738                                               0

In [ ]:
y_pred = model.predict(X_test)

y_pred

520/520 [==============================] - 1s 2ms/step


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
y_test

54731    0
13552    0
43354    0
11691    0
24738    0
        ..
5001     0
26753    0
24658    0
46360    0
9822     0
Name: iuu_caught, Length: 16611, dtype: int64

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

ValueError: ignored

#### Ensemble Techniques

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifier

In [ ]:
easy=EasyEnsembleClassifier()
easy(X_train,y_train)

TypeError: ignored

In [ ]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82382  2916]
 [   14   131]]
0.9657081329073184
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85298
           1       0.04      0.90      0.08       145

    accuracy                           0.97     85443
   macro avg       0.52      0.93      0.53     85443
weighted avg       1.00      0.97      0.98     85443

